<h1>Create book here</h1>



<form method='post'>

    <p>Enter title: </p><input type="text" name="title" value=""/> <br>
    <p>Enter description: </p><input type="text" name="description" value=""/> <br>
    <p>Enter price: </p><input type="text" name="price" value=""/> <br>
    <p>Enter category id: </p><input type="text" name="category_id" value=""/> <br>
    <p>Enter is active: </p><input type="text" name="is_active" value=""/> <br>
    <input type="submit" value="Send">
</form>