<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC</title>
</head>
<body>

    <div class="menu">
        <a href="/index.php?controller=Default&amp;action=index">Home</a>
        <a href="/index.php?controller=Book&amp;action=index">Books</a>
        <a href="/index.php?controller=Default&amp;action=feedback">Contact us</a>
    </div>

    <hr>

    Content

</body>
</html>